# Generated by Django 4.1.4 on 2022-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_is_stuff_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='City of residence'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Country of residence'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='User cover'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='general_info',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='User general information'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos/', verbose_name='User photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User site'),
        ),
    ]
